apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: {{ .Values.namespace }}
  labels:
    app: mlflow
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if and .Values.openShift .Values.openShift.servingCert .Values.openShift.servingCert.enabled }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.openShift.servingCert.secretName }}
  {{- end }}
spec:
  selector:
    app: mlflow
  ports:
    {{- if and .Values.kubeRbacProxy .Values.kubeRbacProxy.enabled }}
    # Public-facing port through kube-rbac-proxy
    - name: https
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: https
    # Internal port for kube-rbac-proxy upstream (MLflow direct)
    - name: https-direct
      protocol: TCP
      port: {{ .Values.service.directPort }}
      targetPort: https-direct
    {{- else }}
    # Direct MLflow port when kube-rbac-proxy is disabled
    - name: https
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: https-direct
    {{- end }}
  type: {{ .Values.service.type }}
