apiVersion: v1
kind: Service
metadata:
  name: mlflow{{ .Values.resourceSuffix }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mlflow{{ .Values.resourceSuffix }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: mlflow{{ .Values.resourceSuffix }}
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: https
  type: {{ .Values.service.type }}
